server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/