server:
  port: 8761

spring:
  application:
    name: roman-blog-eureka

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/