server:
  port: 8010

spring:
  application:
    name: roman-blog-hello

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

info:
  app.name: roman-blog-hello
  company.name: com.example.rom
  build.artifactId: $project.artifactId$
  build.version: $project.version$